Fix: Protocol support
kodemore/kink pull request #54
Opened 2024-02-16 09:39 UTC by jarey

### Current behaviour
Kink current implementation fails to process classes that implement a Protocol. When a Protocol is implemented kink raises an incorrect exception about args/kwargs not matching expected ones.

### Expected behaviour
Kink supports Protocols as part of the class hierarchy/interface implementation, processing dependency injection in the right way even if such elements are included as part of the class hierarchy.

### Content of this PR 
- Fixed bug with Protocol support.
- Include support for tests on CI/CD for python 3.10, 3.11 and 3.12
- Adjusted linting/type-check so it complains with configured checks
- Updated versions of dependencies
- Removed outdated pytests arguments not supported on the updated version of pytest.

2024-03-26 15:25 UTC, barraponto requested changes

2024-03-26 15:25 UTC, barraponto commented on .github/workflows/main.yaml
> +        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "3.12" ]
**suggestion**: drop python 3.7

```suggestion
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
```

2024-04-15 05:22 UTC, dkraczkowski commented
@jarey I just wanted to take a moment to extend my heartfelt thanks for your contribution. Your support and effort truly made my day much better.

2024-04-15 05:23 UTC, dkraczkowski commented
@jarey could you please bump version by running `poetry version minor` command in your terminal/cli?

2024-04-15 05:26 UTC, merged